### ISSUE TITLE
Problem while compiling assets

### ISSUE THREAD

**Issue by firaskafri** [raccoongang/themex_script#1]
```
mkdir_p path('/edx/app/edxapp/themes/Comp_Theme/lms/static/css')
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 196, in _run_task
    return do_task()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/paver/tasks.py", line 193, in do_task
    return func(**kw)
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 499, in compile_sass
    timing_info=timing_info
  File "/edx/app/edxapp/edx-platform/pavelib/assets.py", line 583, in _compile_sass
    output_style=output_style,
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/sass.py", line 644, in compile
    raise CompileError(v)
CompileError: Error: File to import not found or unreadable: lms/static/sass/lms-main
       Parent style sheet: /edx/app/edxapp/themes/Comp_Theme/lms/static/sass/lms-main-rtl.scss
        on line 4 of ../themes/Comp_Theme/lms/static/sass/lms-main-rtl.scss
>> @import 'lms/static/sass/lms-main';
```

**Comment by Tanaha** [comment]
We have updated a script, please try it on now.

**Comment by dgamanenko** [comment]
the problem was in theme template (not in installation script) - now it fixed

**Comment by divyanshu9** [comment]
@dgamanenko  How did you fix it?, i'm having same issue with installing Standform theme on ironwood.
